openapi: 3.0.2
info:
  title: image
  description: A simple service to get image specifications as an example of using OpenAPI 3.0
  license:
    name: Apache 2.0
  version: 0.0.1

servers:
  - url: http://localhost:8080/cloudmesh

paths:
  /image/{cloud_name}:
    get:
      summary: Returns list of images for the cloud
      operationId: python.get_python_version
      responses:
        '200':
          description: cpu info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/python"

components:
  schemas:
    python:
      type: "object"
      required:
        - "model"
      properties:
        model:
          type: "string"