openapi: 3.0.0
info:
  title: get_processor_name
  description: "The name of the processor"
  version: "1.0"
servers:
  - url: http://localhost:8080/cloudmesh
#host: cloudmesh-kikz76y73q-uc.a.run.app
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-cloudmesh.cloudfunctions.net/helloGET
        protocol: h2
      responses:
        '200':
          description: A successful response
          schema:
            type: string